---
basic_settings:
  site_title: Lawrence Ypil
  site_tagline:
  favicon_image:
  logo_image:

menu_settings:
  menu_items:
    - title: 'About'
      url: '/about'
    - title: 'Publications'
      url: '/publications'
    - title: 'Interviews // Profiles'
      url: '/interviews-profiles'
    - title: 'Events'
      url: '/events'
    - title: 'Selected Works'
      url: '/selected-works'
    - title: 'Contact'
      url: '/contact'

contact_settings:
  form_action: ''
  confirmation_url:
  email_subject:
  send_button_text:

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/lawrenceypil/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: 'https://www.amazon.com/Experiment-Tropics-Lawrence-Lacambra-Ypil/dp/0982814259'
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

advanced_settings:
  ajax_loading: true
